Feature/#2 add time stack view UI
TheSwiftist/TimeStacks pull request #3
Opened 2022-11-22 14:18 UTC by asong57

스택 추가화면 기본 UI 프로토타입 구현하였습니다.

- Timer 버전을 DatePicker 활용해서 구현하였고, Clock 버전은 추후에 어떻게 구현할지 정해서 구현할 예정입니다.

- View와 ViewModel 분리 작업은 차후 진행하겠습니다,,

2022-11-25 09:10 UTC, junbangg requested changes
수고하셨습니당🙌

2022-11-25 09:10 UTC, junbangg commented on TimeStacks/TimeStacks/Presentation/Plus/StackPlusView.swift
> +                }).foregroundColor(.black)
요기 action은 그냥 잠시 비워두신거죠???

2022-11-25 09:10 UTC, junbangg commented on TimeStacks/TimeStacks/Presentation/Plus/StackModel.swift
> +struct Stack: Identifiable {
요 친구는 나중에 코드 합치면서 없어지겠죠??

2022-11-25 09:10 UTC, junbangg commented on TimeStacks/TimeStacks/Presentation/Plus/StackPlusView.swift
> +    private let data = StackData()
생성자 뚫어주는건 어떨까요?? 밖에서 어떻게 쓰일지는 모르겠지만

2022-11-25 09:10 UTC, junbangg commented on TimeStacks/TimeStacks/Presentation/Plus/StackPlusView.swift
> +    var body: some View {
아무래도 뷰 그리는 코드가 이렇게 길어지는 경우가 많을것 같은데 적당히 Subview 타입으로 나눌 수 있는 기준을 수립하는건 어떨까요???🤔
가독성, 재사용성, 유지보수성을 위해서??

2022-11-25 09:10 UTC, junbangg commented on TimeStacks/TimeStacks/Presentation/Plus/StackPlusView.swift
> +    var body: some View {
위 코멘트에서 이어지는 이야기지만 body 에 있는 코드를 쫙 읽으면서 어떤 뷰에 해당되는 코드인지 짐작하는것보다 그냥 타입으로 적당히 묶어내면 가독성이 좋아질것 같네요

적당히 mark주석으로 색인을 만드는것도 나쁘지 않을것 같다는 생각도 드네요!
요건 만나서 함께 이야기 해보면 좋을것 같네요:)

2022-11-25 09:10 UTC, junbangg commented on TimeStacks/TimeStacks/Presentation/Plus/StackPlusView.swift
> +                .font(.system(size: 13))
줄바꿈, 메서드 체이닝 줄바꿈에 대한 컨벤션을  함께 정하면 좋을것 같네요(여기가 뭐가 이상한건 아니고 그냥 여기 보면서 생각이 들어서 남겨요ㅎㅎ)

2022-11-25 09:10 UTC, junbangg commented on TimeStacks/TimeStacks/Presentation/Plus/StackPlusView.swift
> +                if isTimerVersion {
요런식으로 분기가 생겨서 뷰가 결정되는 코드는 메서드로 묶어내는것도 괜찮을갓 같네용

2022-11-25 09:10 UTC, junbangg commented on TimeStacks/TimeStacks/Presentation/Plus/StackPlusView.swift
> +    let stack: Stack
요건 은닉이 혹시 불가한가요??

2022-11-27 06:31 UTC, asong57 commented on TimeStacks/TimeStacks/Presentation/Plus/StackPlusView.swift
> +                }).foregroundColor(.black)
네네 아직 네비게이션 로직이나 취소하고 어떻게 할지 정해진 게 없어서요!

2022-11-27 06:32 UTC, asong57 commented on TimeStacks/TimeStacks/Presentation/Plus/StackModel.swift
> +struct Stack: Identifiable {
네 맞습니당!

2022-11-27 06:34 UTC, asong57 commented on TimeStacks/TimeStacks/Presentation/Plus/StackPlusView.swift
> +    private let data = StackData()
startDate, endDate, timerTime 이렇게 3개 프로퍼티는 입력화면에서 사용자가 입력한 값 사용하려고 만든 프로퍼티여서 밖에서 필요할지 아직 잘 모르겠네용

data 프로퍼티는 임시로 만든 프로퍼티여서 나중에 삭제될 것 같습니다!

2022-11-27 06:34 UTC, asong57 commented on TimeStacks/TimeStacks/Presentation/Plus/StackPlusView.swift
> +    var body: some View {
좋습니다.. 저도 이 부분이 View 코드가 너무 길어져서 적절히 Subview 나누는 기준을 다음에 정해서 리팩토링하면 좋을 것 같아요!

2022-11-27 06:34 UTC, asong57 commented on TimeStacks/TimeStacks/Presentation/Plus/StackPlusView.swift
> +    var body: some View {
좋습니다!!

2022-11-27 06:35 UTC, asong57 commented on TimeStacks/TimeStacks/Presentation/Plus/StackPlusView.swift
> +                if isTimerVersion {
좋은 것 같습니다!

2022-11-27 06:36 UTC, asong57 commented on TimeStacks/TimeStacks/Presentation/Plus/StackPlusView.swift
> +    let stack: Stack
가능합니다! 나중에 데이터베이스 추가하면 사라질 struct기는 합니당

2022-11-27 06:37 UTC, asong57 commented on TimeStacks/TimeStacks/Presentation/Plus/StackPlusView.swift
> +    let stack: Stack
가능합니다! 👍

2023-01-28 08:44 UTC, junbangg approved these changes
확인했습니다

2023-01-28 09:41 UTC, merged